ci configuration change

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -43,18 +43,18 @@ jobs:
       - name: "Step 5: Run Lint"
         run: make lint
 
-      - name: Get IP
-        id: getip
-        run: echo "::set-output name=ip::$(hostname -I | awk '{print $1}')"
-
-      - name: Print IP
-        run: |
-          echo "IP Address: ${{ steps.getip.outputs.ip }}"    
 
       - name: "Step 6: Run Unit Tests"
         run: |
           export RUN_IN_DIND=true
           make test
+          if [ $? -ne 0 ]; then
+            echo "Unit tests failed. Debugging..."
+            echo "Checking running Docker containers..."
+            docker ps
+            # Add more commands here to print additional debug information if necessary
+          fi
+
 
       - name: "Step 7: Run e2e  Tests"
         run: make test-e2e
